spring:
  datasource:
    username: "root"
    password: "password"
    url: jdbc:mysql://localhost:3306/spring_execise?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.execise.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml